### ISSUE TITLE
Issue 1: User can view list of characters

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/ajax-project#1]
## ⚙️ Feature 1 

> ##### What capability will users have when this feature is merged?

User can view list of characters
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The home page will have preview 20 characters
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 3 46 30 PM](https://user-images.githubusercontent.com/97265272/192393985-94a31305-3d4d-4526-a861-ec4eada4d7ff.png)
![Screen Shot 2022-09-26 at 3 46 52 PM](https://user-images.githubusercontent.com/97265272/192393989-d1470bfb-5e38-4ecd-9850-c9e6af902646.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a div[data-view="all-characters"] to the HTML.
- [x] Create a header element
- [x] Add 'Rick and Morty' image logo into header
- [x] Create a main element
- [x] Create a heading element: 'All Characters'
- [x] Create div elements that will hold the image and name of characters
- [x] Ensure that there are 20 characters displayed
- [x] Retreive the images of the 20 main characters and add them to the image cards
- [x] Retreive the names of the 20 main characters and add them to the images cards
- [x] Ensure there are 2 characters listed per row when on mobile
- [x] Ensure there are 3 characters lister per row when on desktop
- [x] Listen for clicks on individual image
- [x] Add event listener for when image is clicked that will hide contents of main
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
