### ISSUE TITLE
Issue 2: User can view details of specific characters

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/ajax-project#2]
## ⚙️ Feature 2

> ##### What capability will users have when this feature is merged?

User can access character information

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When an image of a character is clicked, the user will be able to access the information of that character

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 12 37 42 PM](https://user-images.githubusercontent.com/97265272/192364721-1aecf92f-4526-4d4b-a073-e95346c53df7.png)
![Screen Shot 2022-09-26 at 12 38 30 PM](https://user-images.githubusercontent.com/97265272/192364870-5153674a-aaef-4134-8844-cb41e856c665.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a div[data-view="character-information"] to the HTML
- [x] Create a div that will hold the image and information of the character
- [x] Retreive the image of the character and store it within the div
- [x] Retrieve the name of the character and store it within a heading element
- [x] Retrieve information on the [status, species, age, location, and episodes]
- [x] Store information onto seperate rows of text 
- [x] Set the display to none and only visible when the character is clicked previously
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
