### ISSUE TITLE
Issue 3: User can view characters based on which episode they appear in

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/ajax-project#3]
## ⚙️ Feature 3

> ##### What capability will users have when this feature is merged?

User can view episode directory
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A collapsable list will contain all episodes oragnized by the season
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 1 12 37 PM](https://user-images.githubusercontent.com/97265272/192371091-00409ccb-25a8-4861-a545-f9dbbd447256.png)
![Screen Shot 2022-09-26 at 2 25 22 PM](https://user-images.githubusercontent.com/97265272/192383869-56be66eb-f73a-4203-bab3-ad08fda953f9.png)
![Screen Shot 2022-09-26 at 1 13 07 PM](https://user-images.githubusercontent.com/97265272/192371100-56f5ad22-23e9-4184-9144-b1ca33bb3874.png)
![Screen Shot 2022-09-26 at 1 13 26 PM](https://user-images.githubusercontent.com/97265272/192371110-d9fac25c-0fe1-4a06-95de-3cd454c03eb7.png)
![Screen Shot 2022-09-26 at 2 25 39 PM](https://user-images.githubusercontent.com/97265272/192383921-92fdd117-6e07-4d71-baff-42ea9fbb1d29.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a div[data-view="episode-directory"] to the HTML.
- [x] Create a nav bar in the header 
- [x] Create a nav item:'All Characters' that will display 'all-characters' and hide all other
- [x] Create a nav item:'Episode Directory' that will display 'episode-directory' and hide all others
- [x] Create a collapsable list with a heading: 'Episode Directory' the seasons 
- [x] Ensure that the collapsable list has 5 sections for each of the 5 seasons named for each season (e.g. 'Season 1 (episodes 1-11)')
- [x] Within the section of the collapsable list create a section that will store the episode name and number
- [x] Retrieve the name and number of episode and store within 
- [x] Listen for clicks on the episode
- [x] Create a div[data-view='episode-appearance'] to the HTML
- [x] Add eventlister for when an episode is clicked that hides content of 'episode-directory' and displays content of episode appearance
- [x] Retreive and create a heading pertaining to the episode that was clicked (e.g. 'Episode 50: Forgetting Sarick Mortshall') 
- [x] Create containers that will store the retrieved character image and name
- [x] Retrieve and store the images and names into container
- [x] Create a portal image element at bottom of page with the footer: 'Back to Episode Directory'
- [x] Listen for clicks on portal image
- [x] Add event listener to portal image that hides the content of episode-apperance and displays episode-directory
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
