### ISSUE TITLE
Issue 4: User can bookmark character

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/ajax-project#4]
## ⚙️ Feature 4

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 2 45 00 PM](https://user-images.githubusercontent.com/97265272/192386806-12c30ae3-71a6-404a-a550-62fe57c6f610.png)

![Screen Shot 2022-09-26 at 2 47 27 PM](https://user-images.githubusercontent.com/97265272/192386841-fd4ccc6c-1b83-4c4f-bb3d-5c4de0a76a36.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Generate heart icons with every character
- [x] Create array that will store the information of the event.target
- [x] Listen for clicks on icon
- [x] Add eventlister for clicks on icon that target the character information and store the information in an array
- [x] Store image and name
- [x] Ensure the fill color of the icon to be rgb (24 255 19) if the character information is inside the array
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
