### ISSUE TITLE
Issue 5: User can view bookmarked characters

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 2 45 36 PM](https://user-images.githubusercontent.com/97265272/192389980-352a4734-7a06-438e-990c-b1cf50e9130c.png)
![Screen Shot 2022-09-26 at 2 45 49 PM](https://user-images.githubusercontent.com/97265272/192389982-da530653-f4c8-452a-b1a6-217cee7bb0ed.png)
![Screen Shot 2022-09-26 at 2 46 40 PM](https://user-images.githubusercontent.com/97265272/192389998-722eb2a6-ebbb-436b-a2e9-9cea2a4a2a71.png)
![Screen Shot 2022-09-26 at 2 47 49 PM](https://user-images.githubusercontent.com/97265272/192390003-a68db138-6e3c-4743-acd4-0618d79afa14.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Create a div[data-view="bookmarks"] to the HTML.
- [x] Create a nav item "BOOKMARKS' to the navbar
- [x] Create a header element: 'Bookmarks'
- [x] Create a portal image element that will act as a placeholder when no character information is present in the array
- [x] Create a text element: 'No characters here! Go into the portal and get to squanching!' that will act as a placeholder when no character information is present in the array
- [x] Listen for clicks on the portal image
- [x] Add event listener on portal image that will hide the dispay of bookmarks and display episode-directory
- [x] When character information is inside array, generate div that will contain image, name, and icon of the character
- [x] When character information is inside array ensure that portal image and placeholder text are hidden
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
